version: '1'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codedthoughts
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: codedthoughts-backend-bootstrap:latest
    restart: always
    build:
      context: ../
      dockerfile: ./dockerfiles/backend-bootstrap.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
    
volumes:
  db_data: {}